extrafont::loadfonts(device="win")
library(ggplot2)
library(tidyverse)
library(readxl)
library(sf)
library(tigris)
library(patchwork)
library(dplyr)
library(cowplot)

setwd("C:/Users/black/Documents/GitHub/art20")

##############################
# Treat Graph
##############################

theme_fancy_map <- function() {
  theme_void(base_family = "IBM Plex Sans") +
    theme(
      plot.title = element_text(face = "bold", hjust = 0.13, size = rel(1.4)),
      plot.subtitle = element_text(hjust = 0.13, size = rel(1.1)),
      plot.caption = element_text(hjust = 0.13, size = rel(0.8), color = "grey50"),
    )
}

bls_2016 <- read_excel(
  "intermediate/objectid.xlsx",
  col_names = c(
    "objectid", "a_o"
  )
) |>
drop_na(objectid)

us_states_path <- "intermediate/shp/Compras_20_B_Julio_2024.shp"
us_states <- st_read(us_states_path)

prov_path <- "intermediate/shp/Provincias.shp"
prov <- st_read(prov_path)

reg_path <- "intermediate/shp/Regional.shp"
reg2 <- st_read(reg_path)

prov <- prov %>%
   filter(Provincia == "Osorno")

reg <- reg2 %>%
  filter(as.numeric(codregion) %in% c(8, 9, 14))


us_states <- us_states %>%
  filter(as.numeric(COD_REGION) %in% c(08, 09, 10, 14) & !PROVINCIA %in% c("CHILOE", "LLANQUIHUE"))
  
us_states$A_O <- as.numeric(as.character(us_states$A_O))


theme_set(
  theme_minimal(base_family = "Arial", base_size = 7)
)

text_override <- theme(
  text = element_text(family = "Arial", size = 7),
  plot.title = element_text(size = 9, face = "bold"),
  plot.caption = element_text(size = 7),
  legend.text = element_text(size = 7),
  legend.title = element_text(size = 7)
)

unemp_map2 <- unemp_map <- ggplot() +
   geom_sf(data = reg, fill = "white", color = "gray") +
   geom_sf(data = prov, fill = "white", color = "gray") +
  geom_sf(data = us_states, aes(fill = A_O), color = NA) +
  coord_sf(crs = st_crs("EPSG:32718")) +
  scale_fill_gradientn(
    colours = c("yellow", "orange", "red"), 
    limits = c(min(us_states$A_O), max(us_states$A_O)),
    guide = "none"
  ) +
  labs(
    fill = "Year",
    title = "b)", caption = NULL
  ) +
  theme_fancy_map() +
  theme(
    legend.position = c(0.86, 0.32),
    legend.direction = "horizontal",
    legend.text = element_text(size = rel(0.55)),
    legend.title = element_text(face = "bold", size = rel(0.7)),
    plot.margin = margin(0, 2, 2, 0, unit = "cm"),
    plot.title = element_text(size = 9, hjust = 0.5, face = "bold")
  ) +
  text_override

chile2 <- ggplot() +
  geom_sf(data = reg2, fill = "white", color = "gray") +
  geom_sf(data = reg, fill = "black", color = "gray", alpha = 0.8) +
  geom_sf(data = prov, fill = "black", color = "gray", alpha = 0.8) +
  coord_sf(
    crs = st_crs("EPSG:32718"),
    xlim = c(200000, 1300000)
  ) +
  theme_fancy_map() +
  labs(title = "a)") +
  theme(
    plot.margin = margin(0, 2, 2, 0, unit = "cm"),
    plot.title = element_text(size = , hjust = 0.8, face = "bold"),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  text_override

hist_legend2 <- ggplot(us_states, aes(x = A_O)) +  
  annotate(
    "rect",
    xmin = 2002, xmax = 2022,
    ymin = 0, ymax = Inf,
    fill = "grey80",
    alpha = 0.5
  ) +
  geom_histogram(
    aes(fill = after_stat(x)),
    binwidth = 1,
    boundary = 0,
    color = "white"
  ) +
  scale_fill_gradient(low = "yellow", high = "red", guide = "none") +
  scale_x_continuous(
    limits = c(min(us_states$A_O, na.rm = TRUE), 2022),
    breaks = seq(min(us_states$A_O, na.rm = TRUE), 2022, by = 5)
  ) +
  labs(
    x = NULL,
    y = "Frequency",
    title = "c)",
    caption = "Treatment by Year"
  ) +
  theme_minimal(base_family = "Arial", base_size = 7) +
  theme(
    axis.text.x = element_text(size = 7, angle = 45, hjust = 1),
    plot.caption = element_text(size = 7, hjust = 0.5, face = "bold"),
    plot.title = element_text(size = 9, hjust = 0.6, face = "bold"),
    panel.grid = element_blank()
  ) +
  text_override

combined_map_hist <- ggdraw() +
  draw_plot(chile2, x = -0.2, y = 0, width = 1, height = 1) + 
  draw_plot(hist_legend2, x = 0.5, y = 0.1, width = 0.4, height = 0.3) +
  draw_plot(unemp_map2, x = 0.612, y = 0.228, width = 0.4, height = 0.9)

ggsave(
  filename = "results/FTAI_map.pdf",
  plot = combined_map_hist,
  device = cairo_pdf,
  width = 180,
  height = 210,
  units = "mm"
)


##############################
#Land Cover Graph
##############################


parse_latex_file <- function(filepath) {
  lines <- readLines(filepath)
  
  table_starts <- which(str_detect(lines, "\\\\begin\\{tabular\\}"))
  table_ends   <- which(str_detect(lines, "\\\\end\\{tabular\\}"))
  
  all_data <- list()
  
  for (t in seq_along(table_starts)) {
    block <- lines[table_starts[t]:table_ends[t]]
    
    header_line <- block[str_detect(block, "^\\s*Cohort\\s*&")][1]
    
    source <- header_line %>%
      str_extract("&.*") %>%         
      str_remove("^&\\s*") %>%       
      str_remove("\\\\\\\\.*$") %>%  
      str_replace_all("\\\\_", "_") %>% 
      str_trim()
    
    data_list <- list()
    i <- 1
    
    while (i <= length(block)) {
      line <- str_trim(block[i])
      
      if (str_detect(line, "^-?\\d+\\s*&") | str_detect(line, "r1vs0\\.FTAI")) {
        
        if (str_detect(line, "r1vs0\\.FTAI")) {
          relative <- 11
        } else {
          relative <- as.integer(str_extract(line, "^-?\\d+"))
        }
        
        coef <- str_extract(line, "&\\s*-?\\d+\\.?\\d*") %>%
          str_remove("&") %>%
          str_trim() %>%
          as.numeric()
        
        error_line <- str_trim(block[i + 1])
        stderr <- str_extract(error_line, "\\(.*?\\)") %>%
          str_remove_all("[()]") %>%
          as.numeric()
        
        data_list[[length(data_list) + 1]] <- data.frame(
          relative = relative,
          coef = coef,
          stderr = stderr,
          source = source
        )
        
        i <- i + 1
      }
      
      i <- i + 1
    }
    
    all_data[[t]] <- bind_rows(data_list)
  }
  
  bind_rows(all_data)
}

file_paths <- c(
  "results/CS_dyn_Fig2.tex"
)

df_all <- lapply(file_paths, parse_latex_file) %>%
  bind_rows()
  
file_paths <- c(
  "results/CS_Table1.tex"
)

df_all2 <- lapply(file_paths, parse_latex_file) %>%
  bind_rows()

rename_fun <- function(x) case_when(
  x == "natural" ~ "Natural Forest",
  x == "plantation" ~ "Plantation Forest",
  x == "grass" ~ "Grassland",
  x == "crop" ~ "Cropland"
)

df_all <- df_all %>% mutate(source = rename_fun(source))
df_all2 <- df_all2 %>% mutate(source = rename_fun(source))

order_levels <- c("Cropland" , "Grassland", "Natural Forest", "Plantation Forest")
labels_full <- c(
  "Cropland",
  "Grassland",
  "Natural Forest",
  "Plantation Forest"
)

df_all$source <- factor(df_all$source, levels = order_levels, labels = labels_full)
df_all2$source <- factor(df_all2$source, levels = order_levels, labels = labels_full)

df_all2 <- df_all2 %>%
  mutate(
    z = coef / stderr,
    p_value = 2 * (1 - pnorm(abs(z))),
    p_label = sprintf("p=%.3f", p_value)
  )
panel_labels <- df_all %>%
  group_by(source) %>%
  summarise(
    x = -10,               
    y = 0.11, 
    .groups = "drop"
  ) %>%
  mutate(
    label = c("a", "b", "c", "d")
  )
LC <- ggplot(df_all, aes(x = relative, y = coef)) +
  
  geom_ribbon(aes(
    ymin = coef - 1.96 * stderr,
    ymax = coef + 1.96 * stderr
  ), fill = "gray80", alpha = 0.5) +
  
  geom_segment(
    aes(x = -10, xend = 10, y = 0, yend = 0),
    linetype = "dashed",
    color = "black",
    inherit.aes = FALSE
  ) +
  
  geom_line(color = "steelblue", linewidth = 0.6) +
  
  geom_point(
    data = df_all2,
    aes(x = relative, y = coef),
    color = "red",
    size = 1.5,
    inherit.aes = FALSE
  ) +
  
  geom_errorbar(
    data = df_all2,
    aes(
      x = relative,
      ymin = coef - 1.96 * stderr,
      ymax = coef + 1.96 * stderr
    ),
    color = "red",
    width = 0.15,
    linewidth = 0.4,
    inherit.aes = FALSE
  ) +
  
  geom_text(
    data = df_all2,
    aes(
      x = relative,
      y = coef - 1.96 * stderr - 0.01,
      label = p_label
    ),
    size = 2,
    vjust = 1,
    family = "Arial",
    inherit.aes = FALSE
  ) +
  
  facet_wrap(~ source) +
  
  scale_x_continuous(
    limits = c(-10, 11),
    breaks = seq(-10, 11, by = 5)
  ) +
  
  labs(
    x = "Time since restitution (years)",
    y = "Treatment Effect (% of Property)"
  ) +
  geom_label(
    data = panel_labels,
    aes(x = x, y = y, label = label),
    hjust = -0.2,
    vjust = 1.2,
    size = 3.6,
    family = "Arial",
    fontface = "bold",
    fill = "white",
    color = "black",
    label.size = 0,
    inherit.aes = FALSE
  ) +
  theme_minimal(base_family = "Arial", base_size = 7) +
  
  theme(
    text = element_text(family = "Arial", size = 7),
    axis.title = element_text(family = "Arial", size = 7),
    axis.text = element_text(family = "Arial", size = 7),
    strip.text = element_text(family = "Arial", size = 7),
    legend.text = element_text(family = "Arial", size = 7),
    legend.title = element_text(family = "Arial", size = 7),
    plot.title = element_text(family = "Arial", size = 7),
    plot.caption = element_text(family = "Arial", size = 7),
    panel.grid.major = element_line(color = "grey85", linewidth = 0.3),
    panel.grid.minor = element_line(color = "grey92", linewidth = 0.2)
  )

LC

ggsave(
  filename = "results/Land_Cover_Balance.pdf",
  plot = LC,
  device = cairo_pdf,
  width = 180,
  height = 180,
  units = "mm"
)

##############################
#Bio Graph
##############################

file_paths <- c(
  "results/CS_dyn_Fig3.tex"
)

df_all <- lapply(file_paths, parse_latex_file) %>%
  bind_rows()
  
file_paths <- c(
  "results/CS_Table_Bio.tex"
)

df_all2 <- lapply(file_paths, parse_latex_file) %>%
  bind_rows()
  
  
rename_fun <- function(x) case_when(
  x == "biodiv" ~ "Biodiversity",
  x == "log_carbon" ~ "Log(Carbon)",
  x == "trees_lowero" ~ "Trees - Low Erosion",
  x == "trees_highero" ~ "Trees - High Erosion"
)

df_all <- df_all %>% mutate(source = rename_fun(source))
df_all2 <- df_all2 %>% mutate(source = rename_fun(source))

order_levels <- c(
  "Biodiversity",
  "Log(Carbon)",
  "Trees - High Erosion",
  "Trees - Low Erosion"
)

labels_full <- c(
  "Biodiversity",
  "Log(Carbon)",
  "Trees - High Erosion",
  "Trees - Low Erosion"
)

df_all$source <- factor(df_all$source, levels = order_levels, labels = labels_full)
df_all2$source <- factor(df_all2$source, levels = order_levels, labels = labels_full)

df_all2 <- df_all2 %>%
  mutate(
    z = coef / stderr,
    p_value = 2 * (1 - pnorm(abs(z))),
    p_label = sprintf("p=%.3f", p_value)
  )

ci_band <- df_all2 %>%
  group_by(source) %>%
  summarise(
    mean_coef = mean(coef),
    mean_stderr = mean(stderr),
    .groups = "drop"
  ) %>%
  mutate(
    ymin = mean_coef - 1.96 * mean_stderr,
    ymax = mean_coef + 1.96 * mean_stderr
  )
panel_labels <- df_all %>%
  group_by(source) %>%
  summarise(
    x = -10,
    y = 0.11,
    .groups = "drop"
  ) %>%
  mutate(
    label = c("a", "b", "c", "d")
  )
BIO <- ggplot(df_all, aes(x = relative, y = coef)) +
  
  geom_ribbon(aes(
    ymin = coef - 1.96 * stderr,
    ymax = coef + 1.96 * stderr
  ), fill = "gray80", alpha = 0.5) +
  
  geom_line(color = "steelblue", linewidth = 0.6) +
  
  geom_point(
    data = df_all2,
    aes(x = relative, y = coef),
    color = "red",
    size = 1.5,
    inherit.aes = FALSE
  ) +
  
  geom_errorbar(
    data = df_all2,
    aes(
      x = relative,
      ymin = coef - 1.96 * stderr,
      ymax = coef + 1.96 * stderr
    ),
    color = "red",
    width = 0.15,
    linewidth = 0.4,
    inherit.aes = FALSE
  ) +
  
  geom_text(
    data = df_all2,
    aes(
      x = relative,
      y = coef - 1.96 * stderr - 0.01,
      label = p_label
    ),
    size = 2,
    vjust = 1,
    family = "Arial",
    inherit.aes = FALSE
  ) +
  
  geom_segment(
    aes(x = -10, xend = 10, y = 0, yend = 0),
    linetype = "dashed",
    color = "black",
    inherit.aes = FALSE
  ) +
  

  
  facet_wrap(~ source) +
  
  scale_x_continuous(
    limits = c(-10, 11),
    breaks = seq(-10, 11, by = 5)
  ) +
  
  coord_cartesian(ylim = c(-0.1, 0.1)) +
  
  labs(
    x = "Time since restitution (years)",
    y = "Treatment Effect"
  ) +
  geom_label(
    data = panel_labels,
    aes(x = x, y = y, label = label),
    hjust = -0.2,
    vjust = 1.2,
    size = 3.6,
    family = "Arial",
    fontface = "bold",
    fill = "white",
    color = "black",
    label.size = 0,
    inherit.aes = FALSE
  )+
  theme_minimal(base_family = "Arial", base_size = 7) +
  theme(
    text = element_text(family = "Arial", size = 7),
    strip.text = element_text(size = 7),
    panel.grid.major = element_line(color = "grey85", linewidth = 0.3),
    panel.grid.minor = element_line(color = "grey92", linewidth = 0.2)
  )

BIO

ggsave(
  filename = "results/Bio.pdf",
  plot = BIO,
  device = cairo_pdf,
  width = 180,
  height = 180,
  units = "mm"
)
##############################
#EVI Graph
##############################
file_paths <- c(
  "results/CS_dyn_Fig4.tex"
)

df_all <- lapply(file_paths, parse_latex_file) %>%
  bind_rows()
  
file_paths <- c(
  "results/CS_Table_EVI.tex"
)

df_all2 <- lapply(file_paths, parse_latex_file) %>%
  bind_rows()
  
rename_fun <- function(x) case_when(
  x == "log_EVIgrass" ~ "Log(EVI) - Grassland",
  x == "log_EVInatural" ~ "Log(EVI) - Natural Forest",
  x == "log_EVIplants" ~ "Log(EVI) - Plantation Forest"
)

df_all <- df_all %>% mutate(source = rename_fun(source))
df_all2 <- df_all2 %>% mutate(source = rename_fun(source))




ci_band <- df_all2 %>%
  group_by(source) %>%
  summarise(
    mean_coef = mean(coef),
    mean_stderr = mean(stderr),
    .groups = "drop"
  ) %>%
  mutate(
    ymin = mean_coef - 1.96 * mean_stderr,
    ymax = mean_coef + 1.96 * mean_stderr
  )
  
df_all2 <- df_all2 %>%
  mutate(
    z = coef / stderr,
    p_value = 2 * (1 - pnorm(abs(z))),
    p_label = sprintf("p=%.3f", p_value)
  )

panel_labels <- df_all %>%
  group_by(source) %>%
  summarise(
    x = -10,
    y = 0.11,
    .groups = "drop"
  ) %>%
  mutate(
    label = c("a", "b", "c")
  )

EVI <- ggplot(df_all, aes(x = relative, y = coef)) +
  
  geom_ribbon(aes(
    ymin = coef - 1.96 * stderr,
    ymax = coef + 1.96 * stderr
  ), fill = "gray80", alpha = 0.5) +
  
  geom_line(color = "steelblue", linewidth = 0.6) +
  
  geom_point(
    data = df_all2,
    aes(x = relative, y = coef),
    color = "red",
    size = 1.5,
    inherit.aes = FALSE
  ) +
  
  geom_errorbar(
    data = df_all2,
    aes(
      x = relative,
      ymin = coef - 1.96 * stderr,
      ymax = coef + 1.96 * stderr
    ),
    color = "red",
    width = 0.15,
    linewidth = 0.4,
    inherit.aes = FALSE
  ) +
  
  geom_text(
    data = df_all2,
    aes(
      x = relative,
      y = coef - 1.96 * stderr - 0.01,
      label = p_label
    ),
    size = 2,
    vjust = 1,
    family = "Arial",
    inherit.aes = FALSE
  ) +
  
  geom_segment(
    aes(x = -10, xend = 10, y = 0, yend = 0),
    linetype = "dashed",
    color = "black",
    inherit.aes = FALSE
  ) +
  
  facet_wrap(~ source, ncol = 1) +
  
  coord_cartesian(ylim = c(-0.1, 0.1)) +
  
  labs(
    x = "Time since restitution (years)",
    y = "Treatment Effect"
  ) +
  
  geom_label(
    data = panel_labels,
    aes(x = x, y = y, label = label),
    hjust = -0.2,
    vjust = 1.2,
    size = 3.6,
    family = "Arial",
    fontface = "bold",
    fill = "white",
    color = "black",
    label.size = 0,
    inherit.aes = FALSE
  )+
  
  theme_minimal(base_family = "Arial", base_size = 7) +
  
  theme(
    text = element_text(family = "Arial", size = 7),
    axis.title = element_text(family = "Arial", size = 7),
    axis.text = element_text(family = "Arial", size = 7),
    strip.text = element_text(family = "Arial", size = 7),
    legend.text = element_text(family = "Arial", size = 7),
    legend.title = element_text(family = "Arial", size = 7),
    plot.title = element_text(family = "Arial", size = 7),
    plot.caption = element_text(family = "Arial", size = 7),
    
    panel.grid.major = element_line(color = "grey85", linewidth = 0.3),
    panel.grid.minor = element_line(color = "grey92", linewidth = 0.2)
  )

EVI

ggsave(
  filename = "results/EVI.pdf",
  plot = EVI,
  device = cairo_pdf,
  width = 180,
  height = 180,
  units = "mm"
)

